name: ci
on:
  push:
    branches:
      - "**"

defaults:
  run:
    # NOTE: A bit stricter than the default bash options used by GitHub Actions
    # (bash --noprofile --norc -e -o pipefail {0})
    shell: bash --noprofile --norc -euo pipefail {0}

# NOTE: Set concurrency for the current workflow to 1
concurrency: ci-${{ github.ref }}-${{ github.workflow }}

jobs:
  build-and-release:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    permissions:
      id-token: write  # Required for OIDC
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: capralifecycle/actions-lib/check-runtime-dependencies@1457d51592743644e6adc8557c89e77571a6d07c # v1.8.0

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: ".node-version"
          cache: "npm"

      - name: install python linter
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # v4.1.0

      # Add NEW setup-python step here for any new python version needed for lambda tests
      # We need a separate installation step for each python version because the
      # Makefile creates venvs for each lambda and needs the interpreters to be pre-installed
      - name: Setup Python 3.14
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.14"

      - name: Install uv via pip
        run: pip install uv

      - name: build project
        run: make ci

      - name: conditionally semantic release
        run: make release
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
