name: update-documentation
on:
  workflow_run:
    workflows: [ci]
    types:
      - completed
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build-documentation:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ".node-version"
          cache: "npm"

      - name: install python linter
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b # v4.0.0

      # Add NEW setup-python step here for any new python version needed for lambda tests
      # We need a separate installation step for each python version because the
      # Makefile creates venvs for each lambda and needs the interpreters to be pre-installed
      - name: Setup Python 3.14
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"

      - name: Install uv via pip
        run: pip install uv

      - name: install dependencies
        run: make ci

      - name: generate documentation
        run: make update-docs

      - name: configure pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: upload documentation artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: ./docs

      - name: deploy documentation to GitHub Pages
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
