name: update-documentation
on:
  workflow_run:
    workflows: [ci]
    types:
      - completed
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build-documentation:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".node-version"
          cache: "npm"

      - name: install python linter
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # v4.1.0

      # Add NEW setup-python step here for any new python version needed for lambda tests
      # We need a separate installation step for each python version because the
      # Makefile creates venvs for each lambda and needs the interpreters to be pre-installed
      - name: Setup Python 3.14
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"

      - name: Install uv via pip
        run: pip install uv

      - name: install dependencies
        run: make ci

      - name: generate documentation
        run: make update-docs

      - name: configure pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: upload documentation artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./docs

      - name: deploy documentation to GitHub Pages
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
